/* Test-only symbol seam for the Milan runtime transaction. */
#pragma once

#define goodix_milan_runtime_gallery_input_new milan_runtime_test_gallery_input_new
#define goodix_milan_runtime_gallery_input_free milan_runtime_test_gallery_input_free
#define goodix_milan_runtime_input_new milan_runtime_test_input_new
#define goodix_milan_runtime_input_set_cancel_check milan_runtime_test_input_set_cancel_check
#define goodix_milan_runtime_input_free milan_runtime_test_input_free
#define goodix_milan_runtime_run milan_runtime_test_run
#define goodix_milan_runtime_output_free milan_runtime_test_output_free
#define goodix_milan_runtime_enrollment_admitted milan_runtime_test_enrollment_admitted
#define goodix_clear_pending_result_report milan_runtime_test_clear_pending_result_report
#define goodix_auth_start milan_runtime_test_auth_start
#define goodix_enroll_start milan_runtime_test_enroll_start

#define goodix_match_serialized_feature_result_queued milan_runtime_harness_match
#define goodix_match_study_feature_queued milan_runtime_harness_study
#define goodix_milan_enrollment_transaction_attempt milan_runtime_harness_enrollment_attempt

#define goodix_maybe_start_reinit_subsm milan_runtime_harness_reinit
#define goodix_scan_start_coordinator_subsm milan_runtime_harness_scan_start
#define goodix_scan_set_disposition milan_runtime_harness_scan_set_disposition
#define goodix_error_indicates_stale_device milan_runtime_harness_stale_error
