#!/usr/bin/env python3
"""Reproduce two synthetic DLL-packed goldens; never accepts external input data."""

import argparse
import fcntl
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
DLL_SHA256 = "6673db3874fea66a58e2da29e371d797b890c767ba0491134d4a372c5b27e3b4"
INPUTS = ("probe.bin", "coverage-gallery.bin", "tie-gallery.bin")
OUTPUTS = tuple(f"{case}-{phase}.bin" for case in ("coverage", "tie")
                for phase in ("match", "study"))
SOURCES = (
    "tests/test-goodix53x5-milan-native-study-inputs.c",
    "tests/test-goodix53x5-milan-state-support.c",
    "tests/test-goodix53x5-milan-state-support.h",
    "tests/test-goodix53x5-milan-state-study-fixtures.c",
    "tests/test-goodix53x5-milan-state-study-assertions.c",
    "tests/test-goodix53x5-milan-state-study-candidates.c",
    "tests/test-goodix53x5-milan-state-study-support.h",
    "tests/test-goodix53x5-milan-state-tests.h",
    "tests/native-study/native.c",
    "tests/native-study/generate.py",
)


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run(*args, **kwargs):
    try:
        result = subprocess.run([str(arg) for arg in args], check=True, text=True,
                                capture_output=True, timeout=120, **kwargs)
    except subprocess.CalledProcessError as error:
        raise ValueError(f"{args[0]} failed ({error.returncode}):\n"
                         f"{error.stdout}\n{error.stderr}") from error
    if result.stderr.strip():
        print(result.stderr.strip())
    return result.stdout.strip()


def windows(path):
    return "Z:" + str(path.resolve()).replace("/", "\\")


def compare(actual, expected, name):
    a, e = actual.read_bytes(), expected.read_bytes()
    if len(a) != len(e):
        raise ValueError(f"{name}: length generated={len(a)} existing={len(e)}")
    if a != e:
        offset = next(i for i, (x, y) in enumerate(zip(a, e)) if x != y)
        raise ValueError(f"{name}: first differing offset {offset:#x}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dll", type=Path, required=True)
    parser.add_argument("--wine-prefix", type=Path, required=True)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--verify", action="store_true",
                      help="compare freshly generated bytes to committed fixtures")
    mode.add_argument("--output", type=Path,
                      help="create a new output directory; never overwrite fixtures")
    args = parser.parse_args()
    dll, prefix = args.dll.resolve(), args.wine_prefix.resolve()
    if sha(dll) != DLL_SHA256:
        raise ValueError("DLL does not match the approved 2.0.310.900 SHA-256")
    if not all((prefix / name).is_file() for name in ("system.reg", "user.reg")):
        raise ValueError("an initialized existing Wine prefix is required")
    if not (prefix / "drive_c").is_dir() or (prefix / "dosdevices/z:").resolve() != Path("/"):
        raise ValueError("existing Wine prefix must have drive_c and Z: mapped to /")
    if args.output and (args.output.exists() or not args.output.parent.is_dir()):
        raise ValueError("output must not exist and its parent must exist")

    # Use this worktree's freshly built overlay, never an arbitrary exporter or input.
    source = ROOT / ".build/libfprint"
    driver_files = sorted((ROOT / "drivers/goodix53x5").rglob("*"))
    driver_identity = hashlib.sha256()
    for path in driver_files:
        if path.is_file():
            relative = path.relative_to(ROOT).as_posix()
            compare(path, source / "libfprint" / relative, relative)
            driver_identity.update(f"{relative}\0{sha(path)}\n".encode())
    for relative in SOURCES:
        if relative.startswith("tests/test-"):
            compare(ROOT / relative, source / relative, relative)
    run("ninja", "-C", source / "builddir", "tests/goodix53x5-native-study-inputs")

    cache = Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache")) / "milan-parity"
    cache.mkdir(parents=True, exist_ok=True)
    # Identical resolved-prefix lock naming to tools/milan-parity/native-runner.
    lock_path = cache / ("wine-prefix-" + hashlib.sha256(str(prefix).encode()).hexdigest() + ".lock")
    with tempfile.TemporaryDirectory(prefix="native-study-", dir=ROOT / ".build") as temporary:
        work = Path(temporary)
        generated = work / "generated"
        repeated = work / "repeated"
        generated.mkdir()
        repeated.mkdir()
        run(source / "builddir/tests/goodix53x5-native-study-inputs", generated)
        executable = work / "native-study.exe"
        compiler = "x86_64-w64-mingw32-gcc"
        run(compiler, "-std=c17", "-O2", "-Wall", "-Wextra", "-municode",
            HERE / "native.c", "-o", executable)
        env = dict(os.environ, WINEPREFIX=str(prefix), WINEDEBUG="-all",
                   WINEDLLOVERRIDES="winemenubuilder.exe=d")
        observations = {}
        with lock_path.open("a+b") as lock:
            fcntl.flock(lock, fcntl.LOCK_EX)
            wine_version = run("wine", "--version", env=env)
            for case, selected in (("coverage", 3), ("tie", 1)):
                logs = []
                for destination in (generated, repeated):
                    logs.append(run("wine", executable, windows(dll),
                                    windows(generated / "probe.bin"),
                                    windows(generated / f"{case}-gallery.bin"),
                                    windows(destination / f"{case}-match.bin"),
                                    windows(destination / f"{case}-study.bin"),
                                    selected, env=env))
                if logs[0] != logs[1]:
                    raise ValueError(f"{case}: native outcome logs changed on repetition")
                observations[case] = logs[0]
            for name in OUTPUTS:
                compare(generated / name, repeated / name, name + " native repeat")

        provenance = {
            "schema": "goodix-synthetic-native-study/v1",
            "origin": "mathematical test generators only; no personal biometric data or derivatives",
            "scope": "two competing-candidate serialized matcher-to-study cases; type12/profile9",
            "dll": {"sha256": DLL_SHA256, "package_version": "2.0.310.900"},
            "native": {"matcher_rva": "0x5edb0", "study_rva": "0x44fc0",
                       "packer": ["templateGetPackedSize", "templatePack"],
                       "repetitions_per_case": 2, "observations": observations},
            "wine": wine_version,
            "mingw": run(compiler, "-dumpfullversion"),
            "input_driver_source_sha256": driver_identity.hexdigest(),
            "sources": {name: sha(ROOT / name) for name in SOURCES},
            "artifacts": {name: {"size": (generated / name).stat().st_size,
                                 "sha256": sha(generated / name)} for name in INPUTS + OUTPUTS},
        }
        (generated / "provenance.json").write_text(json.dumps(provenance, indent=2, sort_keys=True) + "\n")
        if args.verify:
            for name in INPUTS + OUTPUTS:
                compare(generated / name, HERE / "fixtures" / name, name)
            # Toolchain/source changes may reproduce the same contract. Report them,
            # while leaving the original provenance untouched.
            old = json.loads((HERE / "fixtures/provenance.json").read_text())
            for key in ("schema", "dll", "native", "artifacts"):
                if old.get(key) != provenance[key]:
                    raise ValueError(f"existing provenance does not match native evidence: {key}")
            for key in provenance:
                if old.get(key) != provenance[key]:
                    print(f"provenance differs: {key} (existing record retained)")
            print("Verified all 7 fixed artifacts; both native repetitions byte-identical.")
        else:
            shutil.copytree(generated, args.output)
            print(f"Generated 7 synthetic artifacts and provenance in {args.output}")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, subprocess.SubprocessError) as error:
        raise SystemExit(str(error)) from error
